version: 0.0
os: linux
files:
  - source: .
    destination: /data/app/assessment-hahow
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
   - location: scripts/run.sh
     timeout: 300
     runas: root
